### ISSUE TITLE
動くものレイヤ実装

### ISSUE THREAD

**Issue by koheiasami** [TeamLS/LastSupper#115]
BASEMENT-corridortosmoke にある
imgをカスタムプロパティに追加
Resources_original/img/obj/内のファイル名を指定する

後でResource/img/obj.plistに移す

**Comment by Huehara** [comment]
ごめん
動く物レイヤーのしよう追加で
動く物レイヤーのオブジェクトには当たり判定は無しで
動く物が動くときにも、「他の当たり判定は無視して動ける」
ようにしといてください

**Comment by koheiasami** [comment]
#136
