### ISSUE TITLE
パーティの当たり判定

### ISSUE THREAD

**Issue by Huehara** [TeamLS/LastSupper#126]
パーティに追加された瞬間から当たり判定解除を希望
追加されてからマップまたぐまでの間、当たり判定が残ってるから主人公が動けない

時間がかかるならやらなくてもいい

**Comment by Huehara** [comment]
パーティがいると上手くマップ移動ができない件についても

**Comment by koheiasami** [comment]
上の件は直したけど、下の件は思ったより闇が深いのであとでやる

**Comment by koheiasami** [comment]
#153
