### ISSUE TITLE
charaMoveの追加

### ISSUE THREAD

**Issue by Huehara** [TeamLS/LastSupper#130]
{
　"type":"charaMove",
　"objID:"動かすもののobjID",　　(String)
　"x":x座標    　　 (int)
　"y":y座標　　　　（int）
　"speed":速さ　　(int)
}

基本キャラムーブトゥーと同じ
で動くものレイヤーに登録された画像が
指定された座標に、主人公の歩行の指定された数字倍の速さで、
歩行グラフィックなしで動く

**Comment by koheiasami** [comment]
#142
