### ISSUE TITLE
セーブ昨日にBGMの記憶も追加希望

### ISSUE THREAD

**Issue by Huehara** [TeamLS/LastSupper#131]
一度鳴らしたBGMがセーブして、続きからにすると消えてしまうので

現在鳴らしているBGMも一緒にセーブして、
「つづきから」を選んだ時に
トリガー0で
"type":"playBGM",
"file":"記憶したBGM名"
と同じ効果を施すようにして欲しい

（普通に鳴らしたBGMと同じように
"type":"stopBGM",
"file":"指定されたBGM名
で消せるように)

**Comment by inosy22** [comment]
了解、これならわりとすぐできると思う。

**Comment by inosy22** [comment]
BGMのセーブは複数対応？
