### ISSUE TITLE
トロフィー通知が消えない

### ISSUE THREAD

**Issue by Huehara** [TeamLS/LastSupper#171]
トロフィーの通知が一度出たら消えない
音はならないけど画面の右上に出続けてる

**Comment by Huehara** [comment]
消えるまでマップ移動せずに待ってれば消えるけど、
消える前にマップ移動したら、通知消えずに残ってるっぽい

**Comment by Huehara** [comment]
あとアプリ閉じて、起動し直した状態でトロフィー獲得条件満たすと、
一度通知されたトロフィーの通知がまた来る。

50回セーブして「チキン料理人」獲得して、
アプリ閉じて再起動して
通算51回目のセーブしたらまた「チキン料理人」の通知くる
みたいな

**Comment by inosy22** [comment]
チキン料理人は俺のミスっぽいな
