### ISSUE TITLE
暗号イベ2回ミスったら落ちる

### ISSUE THREAD

**Issue by Huehara** [TeamLS/LastSupper#188]
88624de
のセーブデータ5で

**Comment by inosy22** [comment]
これは連打イベじゃなくてパスワードイベだよね？
なんかバグっぽい

**Comment by Huehara** [comment]
そうだごめん
タイトル修正した

**Comment by inosy22** [comment]
暗号イベ自体にバグはなかったみたい
ここミスってる
https://github.com/TeamLS/LastSupper/blob/uehara/Resources/event/NORTH-1F-barn.json#L82

**Comment by Huehara** [comment]
スクリプトいのすが直した？

**Comment by inosy22** [comment]
直してないよ、前に履歴見たら上原がなおしたコミットしてた気がするけど
