### ISSUE TITLE
カウントダウンイベで落ちる

### ISSUE THREAD

**Issue by Huehara** [TeamLS/LastSupper#189]
カウントダウンイベで
equip指定したときに落ちる

equipの仕様って前作と変わってたっけ？

a932de6
のセーブデータ9
が該当データ

**Comment by inosy22** [comment]
カウントダウンイベはstopCountなくすと落ちなくなるね

**Comment by inosy22** [comment]
こっちはstopCountあっても大丈夫なように直した

**Comment by Huehara** [comment]
修正確認
